export const techOptions = [
  { name: "React", githubSlug: "react", type: "devicon" },
  { name: "Node.js", githubSlug: "nodejs", type: "devicon" },
  { name: "MongoDB", githubSlug: "mongodb", type: "devicon" },
  { name: "JavaScript", githubSlug: "javascript", type: "devicon" },
  { name: "TypeScript", githubSlug: "typescript", type: "devicon" },
  { name: "HTML5", githubSlug: "html5", type: "devicon" },
  { name: "CSS3", githubSlug: "css3", type: "devicon" },
  { name: "Next.js", githubSlug: "nextjs", type: "devicon" },
  { name: "Tailwind CSS", githubSlug: "tailwindcss", type: "devicon" },
  { name: "Python", githubSlug: "python", type: "devicon" },
  { name: "C++", githubSlug: "cplusplus", type: "devicon" },
  { name: "Git", githubSlug: "git", type: "devicon" },
  { name: "GitHub", githubSlug: "github", type: "devicon" },
  { name: "Docker", githubSlug: "docker", type: "devicon" },
  { name: "PostgreSQL", githubSlug: "postgresql", type: "devicon" },
  { name: "Firebase", githubSlug: "firebase", type: "devicon" },
  { name: "Express.js", githubSlug: "express", type: "shields" },
  { name: "Redux", githubSlug: "redux", type: "shields" },
  { name: "SASS", githubSlug: "sass", type: "devicon" },
]